import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Bathroom Services</title>
        {/* Bootstrap CSS */}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossOrigin="anonymous" />
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/outfit" />
        <link rel="stylesheet" href="https://fonts.cdnfonts.com/css/space-grotesk" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />
        <link rel="stylesheet" href="/style.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="whtsapp_btn">
          <Link href="https://wa.me/+971524474455">
            <img src="/images/whatsapp.png" alt="Whatsapp Button" title="WhatsApp" />
          </Link>
        </div>

        <nav className="navbar navbar-expand-lg bg-body-tertiary custom_nav">
          <div className="container">
            <Link className="navbar-brand" href="/">LOGO</Link>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="navbar-collapse" id="navbarTogglerDemo02">
              <ul className="navbar-nav m-auto mb-2">
                <li className="nav-item">
                  <Link className="nav-link active" aria-current="page" href="/">Home</Link>
                </li>

                {/* <!-- Services Dropdown --> */}
                <li className="nav-item dropdown">
                  <a className="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Services
                  </a>

                  <ul className="dropdown-menu custom-dropdown">
                    <li><Link className="dropdown-item" href="/service/gypsum-ceiling-works">Gypsum Ceiling Works</Link></li>
                    <li><Link className="dropdown-item" href="/service/partition-and-drywall-installation">Partition & Drywall Installation</Link></li>
                    <li><Link className="dropdown-item" href="/service/gypsum-wall-cladding-and-panelling">Gypsum Wall Cladding & Panelling</Link></li>
                    <li><Link className="dropdown-item" href="/service/cornices-mouldings-and-decorative-works">Cornices, Mouldings & Decorative Works</Link></li>
                    <li><Link className="dropdown-item" href="/service/gypsum-painting-and-finishing">Gypsum Painting & Finishing</Link></li>
                    <li><Link className="dropdown-item" href="/service/cabinet-refacing-and-painting-a-fresh-look-without-the-full-renovation">Cabinet Refacing & Painting</Link></li>
                    <li><Link className="dropdown-item" href="/service/lighting-and-electrical-setup-illuminate-your-kitchen-elevate-your-experience">Lighting & Electrical Setup</Link></li>
                    <li><Link className="dropdown-item" href="/service/kitchen-plumbing-and-drainage-the-backbone-of-a-functional-kitchen">Kitchen Plumbing & Drainage</Link></li>
                    <li><Link className="dropdown-item" href="/service/ventilation-and-hood-installation-breathe-easy-with-a-cleaner-healthier-kitchen">Ventilation & Hood Installation</Link></li>
                    <li><Link className="dropdown-item" href="/service/modular-kitchen-units-flexible-functional-and-designed-for-modern-living">Modular Kitchen Units</Link></li>

                    <li><Link className="dropdown-item" href="/services">All Services</Link></li>
                  </ul>
                </li>

                <li className="nav-item">
                  <Link className="nav-link" href="/about-us">About Us</Link>
                </li>

                {/* <li className="nav-item">
                  <Link className="nav-link" href="/blogs">Blogs</Link>
                </li> */}

                <li className="nav-item">
                  <Link className="nav-link" href="/contact-us">Contact Us</Link>
                </li>

              </ul>
              <form className="d-flex" role="search">
                <Link href="/contact-us" className="btn btn-primary main_btn">Book Consult<span className="arrow_btn3"><img src="/images/arrow.png" /></span></Link>
              </form>
            </div>
          </div>
        </nav>

        {children}

        <footer className="text-white py-5">
          <div className="container">
            <div className="row">
              <div className="col-md-3 mb-4">
                <h6 className="" style={{ color: "#ffffff", fontSize: "25px" }}>LOGO</h6>
                <p className="">At [Company], we believe every wall has the potential to inspire. With a focus on quality, precision, and design, we offer professional gypsum services that elevate spaces and reflect your unique style. From homes to commercial properties, we turn color into craftsmanship one project at a time.</p>
              </div>

              <div className="col-md-3 mb-4">
                <h6 className="" style={{ color: "#84ace5" }}>Quick Links</h6>
                <ul className="list-unstyled">
                  <li><Link href="/about-us" className="text-decoration-none">About Us</Link></li>
                  <li><Link href="/services" className="text-decoration-none">Services</Link></li>
                  {/* <li><Link href="/blogs" className="text-decoration-none">Blogs</Link></li> */}
                  <li><Link href="/contact-us" className="text-decoration-none">Contact Us</Link></li>
                </ul>
              </div>

              <div className="col-md-3 mb-4">
                <h6 className="" style={{ color: "#84ace5" }}>Contact now</h6>
                <p className="mb-1"><span className="text-white">Address</span></p>
                <p className="">UAE, Dubai</p>
                <p className="mb-1"><span className="text-white">Phone</span></p>
                <p className="">+971 52 447 4455</p>
              </div>

              <div className="col-md-3 mb-4">
                <h6 className="" style={{ color: "#84ace5" }}>Services</h6>
                <ul className="list-unstyled">
                  <li><Link href="/service/lighting-and-electrical-setup-illuminate-your-kitchen-elevate-your-experience" className="text-decoration-none">Lighting & Electrical Setup</Link></li>
                  <li><Link href="/service/kitchen-appliance-installation-seamless-safe-and-professional" className="text-decoration-none">Kitchen Appliance Installation</Link></li>
                  <li><Link href="/service/modular-kitchen-units-flexible-functional-and-designed-for-modern-living" className="text-decoration-none">Modular Kitchen Units</Link></li>
                  <li><Link href="/service/smart-kitchen-solutions" className="text-decoration-none">Smart Kitchen Solutions</Link></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>

        <footer className="text-white text-center py-4">
          <div className="container">
            <p className="mb-0">Copyright © 2025 by Company name</p>
          </div>
        </footer>

        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" strategy="beforeInteractive" />
        <Script src="https://code.jquery.com/jquery-3.6.0.min.js" strategy="beforeInteractive" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
